services:
  frontend-web:
    restart: unless-stopped
    image: app-frontend-web-${APP_NAME}:${APP_TAG} 
    container_name: frontend-web-${APP_NAME}
    build:
      context: ../
      dockerfile: DockerfileFrontendWeb
      target: node-dev-frontend-web
    environment:
      - ROLE_NODE=false
    env_file:
      - .env-dev-local
    ports:
      - 8080:8080
    volumes: 
      - ../frontend-web:/var/www/html
      # supervisor & cron
      - ./app/supervisor-frontend-web/conf.d:/home/app/supervisor/conf.d
      # entrypoint
      - ./app/entrypoint-node.sh:/usr/local/bin/entrypoint-node.sh
    networks:
      - internal
      - external
  frontend-dashboard:
    restart: unless-stopped
    image: app-frontend-dashboard-${APP_NAME}:${APP_TAG} 
    container_name: frontend-dashboard-${APP_NAME}
    build:
      context: ../
      dockerfile: DockerfileFrontendDashboard
      target: node-dev-frontend-dashboard
    environment:
      - ROLE_NODE=false
    env_file:
      - .env-dev-local
    ports:
      - 8090:8090
    volumes: 
      - ../frontend-dashboard:/var/www/html
      # supervisor & cron
      - ./app/supervisor-frontend-web/conf.d:/home/app/supervisor/conf.d
      # entrypoint
      - ./app/entrypoint-node.sh:/usr/local/bin/entrypoint-node.sh
    networks:
      - internal
      - external
  backend:
    restart: unless-stopped
    image: app-backend-${APP_NAME}:${APP_TAG} 
    container_name: backend-${APP_NAME}
    build:
      context: ../
      dockerfile: DockerfileBackend
      target: backend-dev 
    environment:
      - ROLE_BACKGROUND=false
      - ROLE_NGINX=true
      - ROLE_PHP_FPM=true
    env_file:
      - .env-dev-local
    ports:
      # - 8000:8000 # Nginx
      - 80:80 # Laravel
      - 57710:57710 # Admin
      - 5173:5173 # Vite Dev
    networks:
      - internal
      - external
    volumes: 
      # Backend
      - ../backend:/var/www/html
      - ../media/backend:/var/www/html/storage
      # Nginx
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/nginx/common:/etc/nginx/common
      - ./app/nginx/conf.d:/etc/nginx/conf.d
      - ./app/nginx/sites-available:/etc/nginx/sites-available
      - ./app/nginx/sites-available/backend.conf:/etc/nginx/sites-enabled/backend.conf
      - ./app/nginx/snippets:/etc/nginx/snippets
      - ./app/nginx/empty:/etc/nginx/empty
      # Admin Panel
      - ../admin:/var/www/admin
      - ./app/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./app/nginx/sites-available/admin.conf:/etc/nginx/sites-enabled/admin.conf
      # PHP 
      - ./app/php-fpm/php-fpm-dev.conf:/etc/php82/php-fpm.d/www.conf
      - ./app/php-fpm/php-dev.ini:/etc/php82/conf.d/custom.ini
      # supervisor & cron
      - ./app/supervisor/conf.d:/home/app/supervisor/conf.d
      - ./app/cron:/home/app/cron
      # entrypoint
      - ./app/entrypoint.sh:/usr/local/bin/entrypoint.sh
  redis:
    image: redis:latest
    container_name: redis-backend-${APP_NAME}
    restart: unless-stopped
    volumes:
      - ./redis/redis-dev.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      TZ: ${TZ}
    networks:
      - internal
  db:
    image: mariadb:11.3.2
    container_name: db-backend-${APP_NAME}
    restart: unless-stopped
    # ports:
    # Uncomment jika tidak ingin ekpsose
    # - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}       
      MYSQL_USER: "${DB_USERNAME}"               
      MYSQL_PASSWORD: "${DB_PASSWORD}"       
      TZ: ${TZ}
    volumes:
      - ./mysql/config/mysql-dev.cnf:/etc/my.cnf
      - ./mysql/datadir:/var/lib/mysql
    networks:
      - internal
      # - external
  pma:
    # Akses dengan http://domain/pma/ (wajib dengan slash)
    image: phpmyadmin/phpmyadmin
    container_name: pma-backend-${APP_NAME}
    restart: unless-stopped
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
      PMA_ABSOLUTE_URI: "http://${DOMAIN_BACKEND}/pma/"
    links:
      - db:db
    networks:
      - internal
  redis-commander:
    container_name: redis-commander-backend-${APP_NAME}
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    environment:
    - REDIS_HOSTS=local:redis:6379
    networks:
      - internal
networks:
  internal:
    name: ${APP_NAME}-${NETWORK}
  external:
    external: true
    name: ${NETWORK}