/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        secondary: {
          900: '#00585C',
          800: '#007D80',
          700: '#009595',
          600: '#17B3A3',
          500: '#30C6B6',
          400: '#4CDCCF',
          300: '#70E3DC',
          200: '#9DEEEA',
          100: '#C7F7F5',
          50: '#E2FCFA',
        },
        themes: {
          900: '#182535',
          800: '#263C54',
          700: '#284664',
          600: '#2D5277',
          500: '#487FAF',
        },
        text: {
          primary: '#101828',
        },
        neutral: {
          grey: '#F2F4F7',
          white: '#FFFFFF',
        },
        grayscale: {
          600: '#667085',
          500: '#98A2B3',
          400: '#D0D5DD',
          300: '#EAECF0',
          200: '#E4E7EC',
          100: '#F9FAFB',
          50: '#FDFDFD',
        },
        danger: {
          900: '#7A1212',
          800: '#A12222',
          700: '#CF2A2A',
          600: '#E23C3C',
          500: '#F04444',
          400: '#F56C6C',
          300: '#F87979',
          200: '#FCAAAA',
          100: '#FDD8D8',
          50: '#FDECEC',
        },
        warning: {
          900: '#7A3C00',
          800: '#9B4900',
          700: '#C25D00',
          600: '#EA7000',
          500: '#FFA000',
          400: '#FFB718',
          300: '#FFD647',
          200: '#FFEA84',
          100: '#FFF8CC',
          50: '#FFFDE6',
        },
        success: {
          900: '#004C0A',
          800: '#016915',
          700: '#038018',
          600: '#05A022',
          500: '#06B526',
          400: '#37CF5A',
          300: '#7AE592',
          200: '#B3F4C6',
          100: '#DFF8E8',
          50: '#F2FCF4',
        },
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'hsl(var(--primary-foreground))',
          900: '#09305F',
          800: '#0F4288',
          700: '#1546C1',
          600: '#1B53FF',
          500: '#2A6FFF',
          400: '#4D89FF',
          300: '#6CA5FF',
          200: '#99C4FF',
          100: '#C6E0FF',
          50: '#E9F5FF',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        head: '#F9FAFB',
        border: 'var(--border)',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'var(--sidebar-background)',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground':
            'hsl(var(--sidebar-primary-foreground))',
          accent: 'var(--sidebar-accent)',
          'accent-foreground':
            'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
          text: 'var(--sidebar-text)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        // Display
        'display-1': ['64px', { lineHeight: '130%' }],
        'display-2': ['58px', { lineHeight: '130%' }],
        'display-3': ['52px', { lineHeight: '130%' }],
        'display-4': ['48px', { lineHeight: '130%' }],
        'display-5': ['44px', { lineHeight: '130%' }],
        // Heading
        h1: ['40px', { lineHeight: '130%' }],
        h2: ['36px', { lineHeight: '130%' }],
        h3: ['32px', { lineHeight: '130%' }],
        h4: ['28px', { lineHeight: '130%' }],
        h5: ['24px', { lineHeight: '130%' }],
        h6: ['20px', { lineHeight: '130%' }],
        // Paragraph
        p1: ['20px', { lineHeight: '150%' }],
        p2: ['18px', { lineHeight: '150%' }],
        p3: ['16px', { lineHeight: '150%' }],
        p4: ['14px', { lineHeight: '150%' }],
        p5: ['12px', { lineHeight: '150%' }],
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
